package modelo;
// Generated 12/03/2018 01:44:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idEmpresa;
     private String nombreEmpresa;
     private String oficinas;
     private String fundacion;
     private Integer numeroempleados;
     private String presidente;
     private String contacto;
     private Set teners = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Empresa(int idEmpresa, String nombreEmpresa, String oficinas, String fundacion, Integer numeroempleados, String presidente, String contacto, Set teners) {
       this.idEmpresa = idEmpresa;
       this.nombreEmpresa = nombreEmpresa;
       this.oficinas = oficinas;
       this.fundacion = fundacion;
       this.numeroempleados = numeroempleados;
       this.presidente = presidente;
       this.contacto = contacto;
       this.teners = teners;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(String oficinas) {
        this.oficinas = oficinas;
    }
    public String getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(String fundacion) {
        this.fundacion = fundacion;
    }
    public Integer getNumeroempleados() {
        return this.numeroempleados;
    }
    
    public void setNumeroempleados(Integer numeroempleados) {
        this.numeroempleados = numeroempleados;
    }
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set getTeners() {
        return this.teners;
    }
    
    public void setTeners(Set teners) {
        this.teners = teners;
    }




}


