package modelo;
// Generated 12/03/2018 01:44:55 PM by Hibernate Tools 4.3.1



/**
 * Tener generated by hbm2java
 */
public class Tener  implements java.io.Serializable {


     private int idTener;
     private Empresa empresa;
     private Vacante vacante;

    public Tener() {
    }

	
    public Tener(int idTener) {
        this.idTener = idTener;
    }
    public Tener(int idTener, Empresa empresa, Vacante vacante) {
       this.idTener = idTener;
       this.empresa = empresa;
       this.vacante = vacante;
    }
   
    public int getIdTener() {
        return this.idTener;
    }
    
    public void setIdTener(int idTener) {
        this.idTener = idTener;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Vacante getVacante() {
        return this.vacante;
    }
    
    public void setVacante(Vacante vacante) {
        this.vacante = vacante;
    }




}


